### ISSUE TITLE
All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters

### ISSUE THREAD

**Issue by DmitriyLyalyuev** [geometer/book_tools#1]
Unexpected error:

``` bash
$ ./create_opds.py samples/catalog.description 
Warning: feed "icon" attribute is not specified
Warning: feed "author_email" attribute is not specified
Traceback (most recent call last):
  File "./create_opds.py", line 221, in <module>
    create_opds(params.description_file, params.output_dir, working_dir)
  File "./create_opds.py", line 193, in create_opds
    add_entry(root, urls, output_dir, working_dir)
  File "./create_opds.py", line 127, in add_entry
    etree.SubElement(entry, etree.QName(NS_ATOM, 'summary'), type='html').text = book.description
  File "lxml.etree.pyx", line 953, in lxml.etree._Element.text.__set__ (src/lxml/lxml.etree.c:44956)
  File "apihelpers.pxi", line 677, in lxml.etree._setNodeText (src/lxml/lxml.etree.c:20273)
  File "apihelpers.pxi", line 1395, in lxml.etree._utf8 (src/lxml/lxml.etree.c:26485)
ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
```

Content of description file:

``` bash
[feed]
id = http://dmitriy.lyalyuev.info/books/
title = Personal library
subtitle = My family lybrary
author_name = Dmitriy Lyalyuev
author_uri = http://dmitriy.lyalyuev.info/

[book]
url = http://dmitriy.lyalyuev.info/books/Veyr_Marsianin.348577.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Frei/Hroniki_Eho/Fray_Hroniki-Eho_8_Tuburskaya-igra.333061.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Frei/Hroniki_Eho/Fray_Hroniki-Eho_6_Obzhora-hohotun-Istoriya-rasskazannaya-serom-Melifaro.202033.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Frei/Hroniki_Eho/Fray_Hroniki-Eho_1_Chub-zemli-Tulanskiy-detektiv.173193.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Frei/Hroniki_Eho/Fray_Hroniki-Eho_3_Neulovimyy-Habba-Hen.173195.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Frei/Hroniki_Eho/Fray_Hroniki-Eho_7_Dar-Shavanaholy-Istoriya-rasskazannaya-serom-Maksom-iz-Eho.262444.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Frei/Hroniki_Eho/Fray_Hroniki-Eho_2_Vlastelin-Mormory.173194.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Frei/Hroniki_Eho/Fray_Hroniki-Eho_5_Gore-gospodina-Gro.173197.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Frei/Hroniki_Eho/Fray_Hroniki-Eho_4_Vorona-na-mostu.173196.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Dzhon_Perkins__Ispoved_ekonomicheskogo_ubiycy.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Berezin_Voyna-2010_1_Voyna-2010-Ukrainskiy-front.177475.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Stratoplan.Ru_Iron_Man.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Roberts_Shantaram.203255.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Zhvaneckiy_Yuzhnoe-leto-Chitat-na-Severe-.358710.fb2.zip

[book]
url = http://dmitriy.lyalyuev.info/books/Buntovskiyi_S._Nezavisimaya_Ukraina_Krah.fb2.zip
```

**Comment by geometer** [comment]
Thanks. Fixed.
